Implement fd_readdir
CraneStation/wasi-common pull request #116
Opened 2019-10-03 17:17 UTC by marmistrz

Obsoletes #71.

This is a redo of #71 - it was easier to redo the change basing on current master than to fix the merge conflicts.

2019-10-15 19:41 UTC, kubkon requested changes
Thanks for the PR! Looks good, just a couple of points I'd like to discuss.

2019-10-15 19:41 UTC, kubkon commented on src/sys/unix/dir.rs
> +    pub fn open<P: ?Sized + NixPath>(
Do we actually need the `NixPath` here at all? Since this is for our internal WASI use only, a standard `&str`/`String` should suffice, am I right? :-)

2019-10-15 19:41 UTC, kubkon commented on src/sys/unix/dir.rs
> +// }
Is there a reason why this is left out here commented out? Or could we safely remove it?

2019-10-15 19:41 UTC, kubkon commented on src/sys/unix/dir.rs
> +    fn into(self) -> crate::hostcalls_impl::FileType {
Just a minor nitpick, but a `use crate::hostcalls_impl::FileType` and `impl Into<FileType>` would look neater here ;-)

2019-10-15 19:41 UTC, kubkon commented on src/sys/unix/dir.rs
> +        use crate::hostcalls_impl::FileType;
Also, if we did a global `use crate::hostcalls_impl::FileType` as suggested in the comment above, we wouldn't need this one here.

2019-10-15 19:41 UTC, kubkon commented on src/sys/unix/dir.rs
> +            if let Err(e) = Errno::result(readdir_r(
Given that `readdir_r` is marked for deprecation, could we use `readdir` here instead? It would unify the implementation between Linux and BSD-style nixes (the latter uses `readdir` in our implementation of `fd_readdir` on BSD-style nixes).

2019-10-15 19:41 UTC, kubkon commented on src/sys/unix/dir.rs
> +    pub fn open<P: ?Sized + NixPath>(
Also, correct me if I'm wrong but I guess `Dir::open` is obsolete for WASI applications since we'll only ever open a path relative to a file descriptor?

2019-10-15 19:41 UTC, kubkon commented on src/sys/unix/dir.rs
> +            assert_eq!(result, ent.as_mut_ptr());
Hmm, could we somehow replace this `assert` with a `Result` instead? I'd really like our codebase to always (if possible) return an actual error (code) rather than panicking with a cryptic error message.

2019-10-15 19:41 UTC, kubkon commented on src/sys/unix/linux/hostcalls_impl.rs
> +        host_buf[0..offset].copy_from_slice(&dirent_raw);
I think this will panic if `host_buf` has length smaller than `offset` ([copy_from_slice](https://doc.rust-lang.org/std/primitive.slice.html#method.copy_from_slice)).

2019-10-15 19:41 UTC, kubkon commented on src/sys/unix/linux/hostcalls_impl.rs
> +    for dirent in vec {
I might be way off base here, but as far as I can see, `vec` will always hold all dir entries from `cookie` onwards, am I correct? AFAIK, the current upstream implementation, on the other hand, should only ever iterate over the number of entries that can fit the provided `host_buf`. Could we also incorporate that here? @sunfishcode what do you think?

2019-10-15 19:44 UTC, kubkon commented
> @kubkon in a subsequent PR, would you like to either (a) adapt the forked `Dir` to work on *BSD so that we can reuse the code between OSes (b) expose a function returning `Vec<Entry>` so that we can reuse just the part consisting of copying data around

@marmistrz After we address any remaining points and land this PR, I'll be happy to redo the BSD implementation in a way that re-uses as much of the functionality introduced in this PR as possible :-)

2019-10-16 08:15 UTC, kubkon commented on src/sys/unix/dir.rs
> +pub struct Dir(ptr::NonNull<libc::DIR>);
Could this be made `pub(crate)` instead of `pub`?

2019-10-16 08:15 UTC, kubkon commented on src/sys/unix/dir.rs
> +pub struct Iter<'d>(&'d mut Dir);
Like above, could this be made `pub(crate)` instead of `pub`?

2019-10-16 08:15 UTC, kubkon commented on src/sys/unix/dir.rs
> +pub struct Entry(dirent);
Like above, could this be made `pub(crate)` instead of `pub`?

2019-10-16 08:15 UTC, kubkon commented on src/sys/unix/dir.rs
> +pub enum Type {
Like above, could this be made `pub(crate)` instead of `pub`?

2019-10-16 08:16 UTC, kubkon commented on src/sys/unix/dir.rs
> +pub struct SeekLoc(libc::c_long);
Like above, could this be made `pub(crate)` instead of `pub`?

2019-10-16 23:16 UTC, sunfishcode commented on src/sys/unix/linux/hostcalls_impl.rs
> +    for dirent in vec {
Yes, that seems true. And in fact, if I'm reading this correctly, this implies there's quadradic behavior here if you're walking through a large directory with a fixed-size buffer doing `fd_readdir` to fill in one buffer at a time, because the number of `fd_readdir` calls is proportional to the size of the directory, and the number of entries each does is proportional to the size of the directory on average.

How hard would it be to teach `fd_readdir_impl` to serialize as it goes, so that it can know when it's reached the end of the buffer and stop? If it makes things easier, I'd say it's worth it to duplicate some code between platforms to help.

2019-10-19 19:30 UTC, marmistrz commented on src/sys/unix/dir.rs
> +    pub fn open<P: ?Sized + NixPath>(
Probably yes. I wanted to introduce as little changes as possible, so that we can easily catch up with upstream if needed. Do you think it would be better to introduce a minimal module instead?

2019-10-19 19:31 UTC, marmistrz commented on src/sys/unix/dir.rs
> +// }
So that it's clear that this was present in the original code. Probably I should've added a comment.

2019-10-19 19:34 UTC, marmistrz commented on src/sys/unix/dir.rs
> +            if let Err(e) = Errno::result(readdir_r(
This is a good argument for straying further away from the original nix implementation. Also see this related Rust issue: https://github.com/rust-lang/rust/issues/34668

2019-10-19 19:36 UTC, marmistrz commented on src/sys/unix/linux/hostcalls_impl.rs
> +    for dirent in vec {
Good catch! We probably should return an iterator, not a `Vec`. I'll fix it.

2019-11-03 16:46 UTC, marmistrz commented on src/sys/unix/dir.rs
> +    pub fn open<P: ?Sized + NixPath>(
This code was removed.

2019-11-03 16:46 UTC, marmistrz commented on src/sys/unix/dir.rs
> +// }
This code was removed.

2019-11-03 16:46 UTC, marmistrz commented on src/sys/unix/dir.rs
> +    fn into(self) -> crate::hostcalls_impl::FileType {
This code was removed.

2019-11-03 16:46 UTC, marmistrz commented on src/sys/unix/dir.rs
> +        use crate::hostcalls_impl::FileType;
This code was removed.

2019-11-03 16:46 UTC, marmistrz commented on src/sys/unix/dir.rs
> +            if let Err(e) = Errno::result(readdir_r(
Let's leave `readdir_r` for the time being, so that we can merge this PR and switch to `readdir` in a subsequent PR.

2019-11-03 16:58 UTC, marmistrz commented on src/sys/unix/linux/hostcalls_impl.rs
> +    for dirent in vec {
This was changed to an iterator.

2019-11-03 17:32 UTC, marmistrz commented on src/sys/unix/dir.rs
> +            assert_eq!(result, ent.as_mut_ptr());
If this assertion fails, then `readdir_r` implementation doesn't adhere to the spec. I added a better panic message here.

2019-11-03 17:32 UTC, marmistrz commented on src/sys/unix/linux/hostcalls_impl.rs
> +        host_buf[0..offset].copy_from_slice(&dirent_raw);
Good catch! Fixed.

2019-11-03 17:50 UTC, marmistrz commented
This is ready for another round of review.

2019-11-03 18:53 UTC, kubkon commented on src/hostcalls_impl/fs.rs
> +    #![allow(unused)] // temporarily, until BSD catches up with this change
Hint, hint, get cracking Jakub! Just a joke, couldn't help myself ;-)

2019-11-03 20:49 UTC, kubkon commented on src/hostcalls_impl/fs.rs
> +    pub fn to_raw(&self) -> Result<Vec<u8>> {
Hmm, I'm wondering here that perhaps `to_wasi_raw` would be a better name than `to_raw`? The latter kinda implies that it could be any sequence of bytes with some internal structure, whereas the former makes it clear that it's going to be a sequence of bytes that can be interpreted correctly on Wasm side. Additionally, a comment here explaining what this sequence of bytes is meant to contain would be great.

2019-11-03 20:52 UTC, kubkon commented on src/hostcalls_impl/fs.rs
> +    pub fn to_raw(&self) -> Result<Vec<u8>> {
Also, I'd consider making the entire method `unsafe` as, after all, we are casting the struct into a sequence of bytes.

2019-11-03 20:54 UTC, kubkon commented on src/sys/unix/dir.rs
> +#![allow(clippy::use_self)]
Is this needed here? Perhaps it would be even better to have this in the main `lib.rs` manifest? A topic for another PR perhaps?

2019-11-03 21:02 UTC, kubkon commented on src/sys/unix/dir.rs
> +    pub(crate) fn from_fd(fd: RawFd) -> Result<Self> {
I'm wondering whether we actually want this exposed to the crate? I'm somewhat leaning towards making this method private to avoid confusion as to which one should be used: `from` or `from_fd`. Also, following the Rust's convention, we should, at the very least, make `from_fd` `unsafe`. I'm not sure whether `from` should also be `unsafe` though. Thoughts?

2019-11-03 21:06 UTC, kubkon commented on src/sys/unix/dir.rs
> +            // for the NUL byte. It doesn't look like the std library does this; it just uses
Would you mind adding a link here to the bit where this resides in the std library?

2019-11-03 21:09 UTC, kubkon commented on src/sys/unix/linux/hostcalls_impl.rs
> +        trace!("     | fd_readdir: doing seekdir to {}", cookie);
Love the `trace` calls here, thanks!

2019-11-03 21:12 UTC, kubkon commented on src/sys/unix/mod.rs
> +#[allow(trivial_numeric_casts)]
Do we actually need this attribute here, or is a leftover perhaps?

2019-11-03 21:20 UTC, kubkon commented on src/sys/windows/hostcalls_impl/fs.rs
> +    let ty = file.metadata()?.file_type();
Should we worry here that `std::fs::metadata` will only allow us to differentiate between a file and a dir on Windows? When determining the type and access rights for a `Handle` in `fdentry_impl`, we use [get_file_type] to discern into more types than a file and a dir, but I'm wondering whether there is any point in doing that here. I'm not that familiar with Windows unfortunately, but perhaps @peterhuene could you offer a word of advice on this?

[get_file_type]: https://github.com/CraneStation/wasi-common/blob/master/winx/src/file.rs#L49

2019-11-03 21:32 UTC, kubkon commented on src/sys/unix/linux/hostcalls_impl.rs
> +    for dirent in vec {
The applied changes look good to me, but I'll hand it over to @sunfishcode to see what he thinks.

2019-11-04 19:57 UTC, marmistrz commented on src/sys/unix/mod.rs
> +#[allow(trivial_numeric_casts)]
Yes and no. I changed those to into conversions, so that they fail on bleeding-edge platforms where they could be lossy.

2019-11-04 19:58 UTC, marmistrz commented on src/sys/unix/dir.rs
> +    pub(crate) fn from_fd(fd: RawFd) -> Result<Self> {
A leftover from the previous implementation, but I definitely agree.

2019-11-04 19:59 UTC, marmistrz commented on src/sys/unix/dir.rs
> +#![allow(clippy::use_self)]
I added it back in the times when I didn't want to stray far from the original implementation.

2019-11-04 22:35 UTC, marmistrz commented on src/sys/windows/hostcalls_impl/fs.rs
> +    let ty = file.metadata()?.file_type();
In the `filestat` family we're not supporting those various types either. WASI doesn't support FIFOs and pipes for the time being. I also think that what `get_file_type` should ideally be a part of [`FileTypeExt`  in libstd](https://doc.rust-lang.org/std/os/windows/fs/trait.FileTypeExt.html)

2019-11-06 17:14 UTC, marmistrz commented on src/sys/unix/dir.rs
> +            // for the NUL byte. It doesn't look like the std library does this; it just uses
Doine.

2019-11-06 17:20 UTC, marmistrz commented on src/hostcalls_impl/fs.rs
> +    pub fn to_raw(&self) -> Result<Vec<u8>> {
> `to_wasi_raw`

That's a good idea. An alternative could possibly be something `serialize_wasi_raw`, but `to_wasi_raw` sound perfectly fine. I also added some docs.

IMO this is fine, just as it's fine to create a raw pointer from a reference, but it's unsafe to try to dereference it. In other words, trying to interpret this sequence of bytes as any kind of object would definitely be unsafe but serializing the object is perfectly safe.

2019-11-06 17:22 UTC, marmistrz commented
I addressed all the comments from the latest review.

2019-11-07 10:22 UTC, kubkon approved these changes
Great job!

2019-11-07 10:23 UTC, kubkon commented
I reckon we're good to go with this one as-is. If we find any areas that need fixing/improving, I suggest we address those in subsequent PRs.

2019-11-07 10:23 UTC, merged