Try to somehow implement clock_res_get on Windows.
CraneStation/wasi-common pull request #124
Opened 2019-10-11 19:23 UTC by marmistrz

I don't like this implementation, but I think it's the best we can do without overly complicating stuff. We depend on the implementation details on `std::time::{SystemTime, Instant}` (on the underlying Windows syscalls). 

While we could avoid it for `ProcessTime` and `ThreadTime` by adding an associated function returning the timer resolution, possibly the same for `Instant` (and wait forever until it's stable), but the problems for `SystemTime` are much more fundamental. We may have to reconsider this part of WASI API.

Depends on #117 and the implementation details of #119.

2019-10-16 08:07 UTC, kubkon commented on src/sys/windows/hostcalls_impl/misc.rs
> +        // (we could possibly emulate it on earlier versions of Windows, see [4])
Should we even worry about Windows versions lower than Windows 8? After all, Microsoft is meant to end the extended support (mainstream is already finished for Windows 7 and 8.1) for Windows 7 by January 2020 (see [this link]).

[this link]: https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet

2019-10-16 09:50 UTC, programmerjake commented on src/sys/windows/hostcalls_impl/misc.rs
> +        // (we could possibly emulate it on earlier versions of Windows, see [4])
I think having a fallback for Windows 7 is a good idea, since there are lots of people who can't/won't upgrade (for example, if they have custom drivers that they can't port to newer versions of Windows).

2019-10-16 10:18 UTC, kubkon commented on src/sys/windows/hostcalls_impl/misc.rs
> +        // (we could possibly emulate it on earlier versions of Windows, see [4])
Fair enough. Still, it would be good to leverage the new syscalls whenever possible. @marmistrz do you think it would be possible to have an implementation that tries to use `GetSystemTimePreciseAsFileTime`, and if that fails, it reverts back to the current implementation? I'm thinking here a mechanism similar to the one we've implemented in @alexcrichton's [filetime] crate.

[filetime]: https://github.com/alexcrichton/filetime/blob/master/src/unix/macos.rs#L94

2019-10-19 19:27 UTC, marmistrz commented on src/sys/windows/hostcalls_impl/misc.rs
> +        // (we could possibly emulate it on earlier versions of Windows, see [4])
We should definitely support Windows 7. According to netmarketshare.com, Windows 7 still has about 35% market share. It's unclear whether or not we should support Windows XP, which has about 2.5% market share (which is incidentally higher than Linux's)

We could, but I'm not sure if we should. Even OpenJDK refused to switch to `GetSystemTimePreciseAsFileTime` this February because of the following issue. See [this link](https://bugs.openjdk.java.net/browse/JDK-8180466) for their rationale.

2019-10-22 15:40 UTC, sunfishcode commented
Unforunately, `SystemTime` is the most important one. My sense is that the approach in this PR is acceptable here, if that's our best option.

`ProcessTime` and `ThreadTime` may end up getting removed from WASI, since we generally don't want to require that WASI programs be one-to-one with host processes or host threads, and I don't know of an efficient way to implement them on popular OS's otherwise.

2019-11-03 17:58 UTC, marmistrz commented
I caught up with latest master.

2019-11-03 20:38 UTC, kubkon commented on src/sys/windows/hostcalls_impl/misc.rs
> +        // (we could possibly emulate it on earlier versions of Windows, see [4])
SGTM!

2019-11-03 20:41 UTC, marmistrz commented
I'll probably need to open an issue in WebAssembly/WASI about these issues with implementation. They may make us reconsider the API spec.

2019-11-03 20:42 UTC, kubkon commented on winx/src/time.rs
> +        cvt(QueryPerformanceFrequency(&mut frequency))?;
Here's a thought. Given that the MSDN docs on `QueryPerformanceFrequency` state that

> The frequency of the performance counter is fixed at system boot and is consistent across all processors. Therefore, the frequency need only be queried upon application initialization, and the result can be cached.

(here's the [link](https://docs.microsoft.com/en-us/windows/win32/api/profileapi/nf-profileapi-queryperformancefrequency)) would it be prudent for us to adhere to this and actually cache the result of the function, and then simply re-use the result rather than perform a syscall to essentially read out the same value over and over? @peterhuene thoughts?

2019-11-03 20:45 UTC, kubkon commented
> I'll probably need to open an issue in WebAssembly/WASI about these issues with implementation. They may make us reconsider the API spec.

I'm not counting that out. However, before do that, perhaps we should consult @peterhuene first? @peterhuene would you have any thoughts on this PR and the discussion in general?

2019-11-03 23:58 UTC, peterhuene requested changes
This looks great and you did some really in-depth investigation into how this could be well-implemented on Windows.  Thanks for that!

Just some general feedback and a requested clarification on what the resolution value for the realtime clock is representing.

2019-11-03 23:58 UTC, peterhuene commented on src/sys/windows/hostcalls_impl/misc.rs
> +fn get_perf_counter_resolution() -> Result<Duration> {
Should this return a `u64` rather than `Duration`?  It seems that the resolution is always expressed as the number of nanoseconds and we do a conversion back to nanoseconds immediately upon calling this function.

2019-11-03 23:58 UTC, peterhuene commented on winx/src/time.rs
> +        cvt(QueryPerformanceFrequency(&mut frequency))?;
I think caching it would be a good idea.

2019-11-03 23:58 UTC, peterhuene commented on src/sys/windows/hostcalls_impl/misc.rs
> +        wasi::__WASI_CLOCK_REALTIME => 55000,
Should this be `55_000_000` if we're representing 55ms (the potential upper-bound of the resolution for `GetSystemTimeAsFileTime`) in nanoseconds?

It might be worth considering the fact that Windows 7 is EOL in a few short months and switch to using the precise API if we think users will want sub-microsecond resolution of the realtime clock, potentially falling back to `std::time::SystemTime` if the precise API is not available.

If we do switch to `GetSystemTimePreciseAsFileTime`, I think we could get away with assuming the "precise" system time resolution is the same as the monotomic resolution since it seems to use QPC for counting the elapsed time since the last timer interrupt.  But if we're not confortable with that, then I think a microsecond (i.e. `1000`) would be a relatively safe upper-bound, much like we're using 55ms here for the imprecise API.

2019-11-04 14:10 UTC, marmistrz commented on src/sys/windows/hostcalls_impl/misc.rs
> +        wasi::__WASI_CLOCK_REALTIME => 55000,
Please see discussion in @kubkon's review from 16th Oct. Feel free to unresolve it if you think it was resolved prematurely.

2019-11-04 17:20 UTC, peterhuene commented on src/sys/windows/hostcalls_impl/misc.rs
> +        wasi::__WASI_CLOCK_REALTIME => 55000,
I'm 👍 with not using a higher precision real time clock.  However, can you verify for me that the value of `55000` is correct?  Is this 55 μs or 55 ms?

2019-11-04 18:32 UTC, marmistrz commented on src/sys/windows/hostcalls_impl/misc.rs
> +        wasi::__WASI_CLOCK_REALTIME => 55000,
Yes, this should definitely be 55ms, thanks for noticing that!

2019-11-05 14:51 UTC, marmistrz commented on winx/src/time.rs
> +        cvt(QueryPerformanceFrequency(&mut frequency))?;
This is definitely a good idea and is fixed now, but requires a somewhat lossy error conversion (but I wouldn't worry about it too much). We're hit by https://github.com/rust-lang/rust/issues/24135.

2019-11-05 17:25 UTC, peterhuene commented on winx/src/time.rs
> +        cvt(QueryPerformanceFrequency(&mut frequency))?;
I wonder if we should only cache it on success rather than caching the error as well.

Additionally, it looks like we could also just panic if it fails:

```
On systems that run Windows XP or later, the function will always succeed and will thus never return zero.
```

2019-11-05 17:51 UTC, marmistrz commented on winx/src/time.rs
> +        cvt(QueryPerformanceFrequency(&mut frequency))?;
I think it's perfectly fine to panic on systems earlier than Windows XP.

2019-11-05 20:00 UTC, marmistrz commented on src/sys/windows/hostcalls_impl/misc.rs
> +fn get_perf_counter_resolution() -> Result<Duration> {
The way I see it, `Instant`s from the stdlib are treated similar to points in an affine space having `Duration`s as its tangent space (aka free vectors) - you can measure the distance between two `Instant`s and also add a `Duration` to an `Instant`. (this is some fuzzy intuition, not a precise statement). Resolution also sounds like a free vector in here, so `Duration` seems semantically fine.

On the other hand, packing and unpacking the integer does no good for code readability, so I think it's a perfectly valid choice to return a `u64`.

2019-11-05 21:10 UTC, peterhuene approved these changes

2019-11-05 22:29 UTC, sunfishcode approved these changes

2019-11-06 15:41 UTC, kubkon approved these changes
Great job, thanks!

2019-11-06 16:02 UTC, merged