Fixes CraneStation/wasmtime#440
CraneStation/wasi-common pull request #137
Opened 2019-10-21 09:18 UTC by kubkon

**This a WIP PR so things might still get adjusted**

This commit introduces a couple of changes/fixes:
* it annotates `log::debug!` messages with "host" to differentiate
  between file descriptors stored on the WASI side (aka the wrappers)
  and those managed by the host (aka the wrapped)
* it fixes CraneStation/wasmtime#440, i.e., incorrect passing of
  file descriptor to `poll_oneoff` where currently errenously we
  pass in the wrapper instead of the wrapped value
* it adds a couple more `log::debug!` macros calls for easier future
  debugging

2019-10-23 19:16 UTC, kubkon commented
OK, this PR is ready for review. Note however that it is (unfortunately) expected to fail as it makes breaking API changes which still need to be addressed in `wasmtime`.

Additionally, this PR is blocked by CraneStation/wasi-misc-tests#38 (i.e., it really should include `misc_testsuite` rewind to the latest upstream when CraneStation/wasi-misc-tests#38 lands).

2019-10-24 14:26 UTC, marmistrz requested changes
I closed #140, let's keep all the refactoring in one PR.

2019-10-24 14:26 UTC, marmistrz commented on src/hostcalls_impl/misc.rs
> +        events_count += 1;
You can just use `events.len()` and avoid mutability. And please avoid the indices, they're not necessary here (the original code also avoids them). See also how it's done in #140.

2019-10-24 14:26 UTC, marmistrz commented on src/sys/unix/hostcalls_impl/misc.rs
> +    input: impl Iterator<Item = Result<host::__wasi_subscription_t>>,
Can we accept `Vec<FdEventData>` and  `Option<ClockEventData>` for timeout as in #140? The conversion code cross-platform code and should not reside in this module.

2019-10-24 14:26 UTC, marmistrz commented on src/sys/unix/hostcalls_impl/misc.rs
> +    let mut fd_events = Vec::new();
See the comment above.

2019-10-24 14:26 UTC, marmistrz commented on src/sys/unix/hostcalls_impl/misc.rs
>      let timeout = timeout.map(|ClockEventData { delay, userdata }| ClockEventData {
We can remove this map and just use `try_into` as in #140.

2019-10-24 14:26 UTC, marmistrz commented on src/sys/unix/hostcalls_impl/misc.rs
> +        vec![]
Then accept `ClockEventData`, not an `Option<ClockEventData>`. Accepting `Option<ClockEventData>` suggests that `None` is a valid value. See how #140 does it.

2019-10-24 14:32 UTC, kubkon commented
> I closed #140, let's keep all the refactoring in one PR.

That's my bad at poorly synchronising efforts between the two of us. Apologies!

2019-10-24 14:33 UTC, kubkon commented on src/sys/unix/hostcalls_impl/misc.rs
> +    input: impl Iterator<Item = Result<host::__wasi_subscription_t>>,
Ah, good idea. Let me refactor it following #140 then!

2019-10-24 14:52 UTC, marmistrz commented on src/sys/unix/hostcalls_impl/misc.rs
> +    input: impl Iterator<Item = Result<host::__wasi_subscription_t>>,
I'd prefer to have one decent refactor commit, but if this is a major blocker and should be merged ASAP, I'm fine with finishing the refactor in a subsequent PR.

2019-10-24 14:54 UTC, kubkon commented on src/sys/unix/hostcalls_impl/misc.rs
> +    input: impl Iterator<Item = Result<host::__wasi_subscription_t>>,
I guess we're not in such a hurry, so let's see how we get on with it :-)

2019-10-24 20:56 UTC, dunnock commented on src/sys/unix/hostcalls_impl/misc.rs
> +                        .get_fd_entry(wasi_fd, host::__WASI_RIGHT_FD_READ, 0)?
This line seems throwing error when at least one bad wasi file descriptor supplied. Should not it rather return event for relevant record with error code EBADF? Since there might be mix of polls subscriptions and some might be valid, while some invalid it is important to return those which are valid too.

I've added relevant test https://github.com/kubkon/wasi-misc-tests/pull/2/commits/ed16186b8d4a762020083c8b36d91b12a96f9580

2019-10-27 19:03 UTC, kubkon commented on src/hostcalls_impl/misc.rs
> +        events_count += 1;
Good point on `events.len()`, thanks! I'm less clear on "avoiding the indices". Are you saying that calling

```rust
*output_slice_cur.next().unwrap() = enc_event(event);
```

is safer than using indices because AFAIK, in this case, both will panic if we exceed the range. Or is it a stylistic concern?

2019-10-27 19:06 UTC, marmistrz commented on src/hostcalls_impl/misc.rs
> +        events_count += 1;
Both. Probably with an `expect` instead of `unwrap`. It's cleaner and it's not possible to use the wrong variable as the index.

2019-10-27 19:09 UTC, kubkon commented on src/sys/unix/hostcalls_impl/misc.rs
> +    input: impl Iterator<Item = Result<host::__wasi_subscription_t>>,
OK, I've now had a closer look at this. We cannot accept `Vec<FdEventData>` as this will be host specific (on *nix, we deal with file descriptors, on Windows it will be handles). However, if we modify `FdEventData` to contain our `Descriptor` struct, then this should be possible to refactor out.

2019-10-27 19:10 UTC, kubkon commented on src/sys/unix/hostcalls_impl/misc.rs
> +                        .get_fd_entry(wasi_fd, host::__WASI_RIGHT_FD_READ, 0)?
Yep, I see it now, thanks!

2019-10-27 20:41 UTC, kubkon commented on src/sys/unix/hostcalls_impl/misc.rs
> +                        .get_fd_entry(wasi_fd, host::__WASI_RIGHT_FD_READ, 0)?
Now that I've included the smoke test CraneStation/wasi-misc-tests#38 in this PR, this seems to be the only (I hope I didn't miss anything!) major thing left before this PR is ready for merging.

2019-10-28 08:48 UTC, kubkon commented on src/sys/unix/hostcalls_impl/misc.rs
> +                        .get_fd_entry(wasi_fd, host::__WASI_RIGHT_FD_READ, 0)?
Here's a question about the spec; would love your comment about this one @sunfishcode. From what I see in the implementation and the spec, the user can link subscriptions with events by the field `userdata` which is present in both and set to the same, user-specified value. Does that mean that we don't have to preserve the order of events relative to the order of the (input) subscriptions? I guess this would make sense especially since in the spec we do say "concurrently poll" [WASI-api#__wasi_poll_oneoff]. And a follow-up question. If indeed `userdata` is used as an identifier for `(subscription, event)` pair, we (purposely) do not enforce uniqueness of `userdata` among the input subscriptions which could very well lead to collisions in the output events, but I guess it is up to the client to enforce the uniqueness?

[WASI-api#__wasi_poll_oneoff]: https://github.com/CraneStation/wasmtime/blob/master/docs/WASI-api.md#__wasi_poll_oneoff

2019-10-29 13:28 UTC, marmistrz commented
@kubkon can we have a more descriptive PR title?

2019-10-30 08:34 UTC, kubkon commented on src/sys/unix/hostcalls_impl/misc.rs
> +                        .get_fd_entry(wasi_fd, host::__WASI_RIGHT_FD_READ, 0)?
OK, I think I now have convinced myself that the order in general will not be preserved nor is expected to be.

2019-10-30 08:57 UTC, kubkon commented
I think we're in a pretty good shape with this now, so I'm gonna go ahead and merge this. If you guys feel that we should still modify something, or something isn't clear, please feel free to submit an issue, and I'll be happy to fix anything that is remaining :-)

2019-10-30 08:58 UTC, merged