Fix fd_readdir on BSD-style nixes
CraneStation/wasi-common pull request #81
Opened 2019-08-28 21:15 UTC by kubkon

The fix was tested on Darwin-XNU and FreeBSD. The change introduces thread-safe cache of `(RawFd, *mut libc::DIR)` pairs so that `libc::fdopendir` syscall is called only once when invoking `fd_readdir` for the first time, and then the pointer to the directory stream, `*mut libc::DIR`, is reused until the matching raw file descriptor is closed.

This fix allows then correct use (and matching to the implementation on Linux kernels) of `libc::seekdir` and `libc::rewinddir` to seek through and rewind the existing directory stream, `*mut libc::DIR`, which otherwise seems to be reset/invalidated every time `libc::fdopendir` is called (unlike on Linux, where this behaviour is not observed).

@sunfishcode @marmistrz to sum up, on BSD-based kernels, we can either go with something similar to the proposed solution in this PR, or we can traverse the entire directory stream from the beginning at every `fd_readdir` call thus doing quadratic work. Let me know your thoughts!

To provide some more context, the following snippet does not behave as expected on BSD-based kernels (although this particular code applies only to Darwin-XNU):

```rust
use std::ffi::CString;
use std::ptr;

fn main() {
    unsafe {
        let name = CString::new(".").unwrap();
        let dir = libc::opendir(name.as_ptr());
        libc::seekdir(dir, 2); // <- no effect on `dir` whatsoever; the "2" here is just an example

        loop {
            println!("loc={:?}", libc::telldir(dir));
            let entry = libc::readdir(dir);
            if entry == ptr::null_mut() {
                println!("errno={}", nix::errno::Errno::last());
                break;
            }
            println!("entry={:?}", *entry);
        }

        libc::closedir(dir);
    }
}
```

Whereas the following snippet successfully employs `seekdir`:

```rust
use std::ffi::CString;
use std::ptr;

fn main() {
    unsafe {
        let name = CString::new(".").unwrap();
        let dir = libc::opendir(name.as_ptr());

        loop {
            println!("loc={:?}", libc::telldir(dir));
            let entry = libc::readdir(dir);
            if entry == ptr::null_mut() {
                break;
            }
            println!("entry={:?}", *entry);
        }

        libc::seekdir(dir, 2); // <- this `seekdir` call is successful

        loop {
            println!("loc={:?}", libc::telldir(dir));
            let entry = libc::readdir(dir);
            if entry == ptr::null_mut() {
                break;
            }
            println!("entry={:?}", *entry);
        }

        libc::closedir(dir);
    }
}

```

2019-08-29 10:38 UTC, marmistrz requested changes

2019-08-29 10:38 UTC, marmistrz commented on src/hostcalls_impl/fs.rs
> +    #[cfg(not(any(target_os = "linux", target_os = "windows")))]
I'd rather be explicit here
```
     #[cfg(any(target_os = "freebsd", target_os = "openbsd", target_os = "netbsd", target_os = "macos")))] 
```
in case we decide to support e.g. Android or Fuchsia in the future. 
The possible values of `target_os` can be found [here](https://docs.rs/platforms/0.2.0/platforms/target/enum.OS.html)

2019-08-29 10:38 UTC, marmistrz commented on src/sys/unix/hostcalls_impl/fs.rs
> +#[cfg(not(target_os = "linux"))]
I'd rather be explicit here. You could also use
```
#[cfg(...)]
mod fd_readdir_impl_bsd {
     ... 
}
#[cfg(...)]
pub use fd_readdir_impl_bsd::fd_readdir;
```
to reduce the number of #[cfg]s

2019-08-29 10:38 UTC, marmistrz commented on src/sys/unix/hostcalls_impl/fs.rs
> +    static ref DIRP_CACHE: Arc<RwLock<HashMap<RawFd, AtomicPtr<libc::DIR>>>> = Arc::new(RwLock::new(HashMap::new()));
Please add a comment why the cache is needed.

2019-09-03 14:57 UTC, alexcrichton commented
Ah sorry I don't really know much about the system-level details here, so I don't think I'd be a great reviewer for this

2019-09-03 22:06 UTC, sunfishcode commented
Instead of a `HashMap<RawFd, *mut libc::DIR>` in a `lazy_static`, would it be possible to store the `*mut libc::DIR` in the `FdEntry`, `FdObject`, or `Descriptor`, whichever is most appropriate? It feels like the `*mut libc::DIR` should be just additional per-file-descriptor state.

2019-09-04 16:47 UTC, kubkon commented
@sunfishcode that’s an excellent idea, thanks!

2019-09-04 16:47 UTC, kubkon commented on src/sys/unix/hostcalls_impl/fs.rs
> +#[cfg(not(target_os = "linux"))]
I like this approach, thanks!

2019-09-09 16:44 UTC, sunfishcode commented on src/fdentry.rs
> +    target_os = "openbsd"
Should these changes apply to "ios" and "dragonfly" too? I guess we can just make our best guess here.

2019-09-09 16:44 UTC, sunfishcode commented on src/sys/unix/hostcalls_impl/fs.rs
> +        dir_stream.replace(AtomicPtr::new(dirp));
A `replace` where you don't use the result is just a store.

2019-09-09 16:44 UTC, sunfishcode commented on src/fdentry.rs
> +        dir_stream: Option<AtomicPtr<libc::DIR>>,
Should this be a `Mutex` rather than `AtomicPtr`, to prevent multiple threads from doing `readdir` at the same time?

2019-09-09 16:44 UTC, sunfishcode commented on src/fdentry.rs
> +)))]
`not(any(lots of stuff))` in a file which also does `any(lots of stuff)` suggests a `cfg_if` macro might be useful.

Alternatively, since code later does `#[cfg(target_os = "linux")]`, should we do that here too?

2019-09-09 16:53 UTC, marmistrz requested changes

2019-09-09 16:53 UTC, marmistrz commented on src/sys/unix/hostcalls_impl/fs.rs
> +        let dirp = unsafe { fdopendir(fd) };
You need to `dup` the fd for fdopendir, see the relevant source code comment in #71.

2019-09-09 17:26 UTC, kubkon commented on src/sys/unix/hostcalls_impl/fs.rs
> +        let dirp = unsafe { fdopendir(fd) };
Good point! Thanks for catching that one!

2019-09-09 17:29 UTC, kubkon commented on src/fdentry.rs
> +    target_os = "openbsd"
"ios" probably yes, "dragonfly" no idea. I've got least experience with the latter actually. But I guess we can add it in and indeed hope for the best ;-)

2019-09-12 21:37 UTC, kubkon commented on src/fdentry.rs
> +)))]
I've now reshuffled the code a bit. Hopefully it's a bit cleaner. I'm not set on this organisation though, so if you feel it should be done in a different way, fire away please!

2019-09-12 21:38 UTC, kubkon commented on src/sys/unix/hostcalls_impl/fs.rs
> +        let dirp = unsafe { fdopendir(fd) };
I've now made sure we clone the `fd` and then close it with `closedir` as prescribed in the man pages :-)

2019-09-12 21:40 UTC, kubkon commented on src/fdentry.rs
> +    target_os = "openbsd"
I've now added both `ios` and `dragonfly` to the list.

2019-09-13 21:15 UTC, sunfishcode reviewed
Looks good! Just a few more minor comments:

2019-09-13 21:15 UTC, sunfishcode commented on src/sys/unix/bsd/hostcalls_impl.rs
> +        | host::__WASI_ADVICE_NORMAL => {}
This is pre-existing, but least some BSD's [do support `posix_fadvise`](https://www.freebsd.org/cgi/man.cgi?query=posix_fadvise&sektion=2&manpath=FreeBSD+8.3-RELEASE), so we should have a TODO comment here.

2019-09-13 21:15 UTC, sunfishcode commented on src/sys/unix/linux/hostcalls_impl.rs
> +        }
This is pre-existing, but I just noticed it now. `readdir_r` returns a positive int on failure, and doesn't set errno.

It would also be good to look into using plain `readdir` instead of `readdir_r`, since [the Linux readdir_r documentation](http://man7.org/linux/man-pages/man3/readdir_r.3.html) says `readdir_r` is deprecated, though we can do that later if you just want to leave a TODO comment or so.

2019-09-13 21:15 UTC, sunfishcode commented on src/sys/unix/bsd/osfile.rs
> +pub struct OsFile {
Can this (and the other `OsFile` implementations, and `DirStream`, be `pub(crate)` to make it clear that this isn't part of the public API?

2019-09-13 21:15 UTC, sunfishcode commented on src/sys/unix/bsd/hostcalls_impl.rs
> +        log::debug!("entry = {:?}", entry);
This looks like a useful `debug!` macro; would you mind adding a similar one in the Linux code?

2019-09-13 21:15 UTC, sunfishcode commented on src/sys/unix/linux/hostcalls_impl.rs
> +    Ok(host_buf_len - left)
This is a minor nit, but the BSD version has a blank line before the `Ok` here, and it's nice to keep the formatting consistent.

2019-09-14 06:45 UTC, kubkon commented on src/sys/unix/bsd/hostcalls_impl.rs
> +        | host::__WASI_ADVICE_NORMAL => {}
Done!

2019-09-14 06:45 UTC, kubkon commented on src/sys/unix/linux/hostcalls_impl.rs
> +        }
Done!

2019-09-14 06:45 UTC, kubkon commented on src/sys/unix/bsd/hostcalls_impl.rs
> +        log::debug!("entry = {:?}", entry);
Done!

2019-09-14 06:45 UTC, kubkon commented on src/sys/unix/linux/hostcalls_impl.rs
> +    Ok(host_buf_len - left)
Done!

2019-09-14 07:22 UTC, marmistrz requested changes
Also, add a comment explaining the purpose of `OsFile` and the scope where it should be used

2019-09-14 07:22 UTC, marmistrz commented on src/fdentry.rs
> +    #[allow(unused)]
Add a comment explaining this supression

2019-09-14 07:22 UTC, marmistrz commented on src/hostcalls_impl/fs.rs
> +        .and_then(|file| FdEntry::duplicate(file))?;
Why is the closure neeeed here?

2019-09-14 07:22 UTC, marmistrz commented on src/sys/unix/bsd/hostcalls_impl.rs
> +
expect? or add a comment why unwrap is ok here.

2019-09-14 07:22 UTC, marmistrz commented on src/sys/unix/bsd/hostcalls_impl.rs
> +        log::debug!("entry = {:?}", entry);
mention  fd_readdir in this `debug!`

2019-09-14 07:22 UTC, marmistrz commented on src/sys/unix/bsd/hostcalls_impl.rs
> +            let ptr = host_buf_ptr.offset(host_buf_offset as isize) as *mut c_void
try_into?

2019-09-14 07:22 UTC, marmistrz commented on src/sys/unix/bsd/osfile.rs
> +    pub dir_stream: Option<Mutex<DirStream>>,
Nitpicking: or RwLock?

2019-09-14 08:00 UTC, kubkon commented on src/hostcalls_impl/fs.rs
> +        .and_then(|file| FdEntry::duplicate(file))?;
Good question. `FdEntry::duplicate` requires `&fs::File` whereas currently, within a `FdEntry::FdObject::Descriptor` we store an `OsFile` which implements a `Deref<Target = fs::File` but it's not enough to convince the compiler that it can deref `file` in the call above into `&fs::File`, hence why the explicit closure here. :-)

2019-09-14 08:01 UTC, kubkon commented on src/sys/unix/bsd/hostcalls_impl.rs
> +
Comment added!

2019-09-14 08:02 UTC, kubkon commented on src/sys/unix/bsd/hostcalls_impl.rs
> +            let ptr = host_buf_ptr.offset(host_buf_offset as isize) as *mut c_void
Done!

2019-09-14 08:16 UTC, marmistrz commented on src/sys/unix/bsd/hostcalls_impl.rs
> +
How about `unwrap_or_else`?

2019-09-14 08:43 UTC, kubkon commented on src/sys/unix/bsd/hostcalls_impl.rs
> +
Yeah, I thought about it. I also considered `get_or_insert_with`, but alas, neither of these allow for the closure to fail with an error, and we need this since we need to duplicate the `File` handle as you rightly pointed out in one of your previous comments. Anyhow, if you do know a way, fire away and I'll be more than happy to change it! :-)

2019-09-14 08:45 UTC, kubkon commented on src/fdentry.rs
> +    #[allow(unused)]
The suppression is there since we actually don't rely on any of this functionality in the lib just yet. This is not to say we definitely will in the future, but it makes the interface of `Descriptor` a little bit more complete. I can either leave the suppression in or simply chuck away the unused `fn`s. I guess personally I'd leave the suppression in for now and decide later if it's needed or not :-)

2019-09-14 08:46 UTC, kubkon commented on src/sys/unix/bsd/osfile.rs
> +pub struct OsFile {
Yep, good catch, thanks! I've changed it to public-private now :-)

2019-09-14 08:49 UTC, marmistrz commented on src/sys/unix/bsd/hostcalls_impl.rs
> +
`.map(Ok).unwrap_or_else(...)?`

2019-09-14 08:52 UTC, kubkon commented on src/sys/unix/bsd/osfile.rs
> +    pub dir_stream: Option<Mutex<DirStream>>,
Ah, now this one's tricky. I actually thought about using `RwLock` but then convinced myself otherwise as AFAICS we'll always require a write lock on the stream since every call to *dir syscall modifies the underlying `dir_ptr`.

2019-09-14 08:54 UTC, kubkon commented on src/sys/unix/bsd/hostcalls_impl.rs
> +
Hmm, interesting. Could it be used with `get_or_insert_with`? I just remembered that we cannot use `unwrap_or_else` as we need to hold onto the duplicated handle and the dir stream ptr after it's first created.

2019-09-14 09:22 UTC, marmistrz commented on src/sys/unix/bsd/hostcalls_impl.rs
> +
pattern match with mutation on None?

2019-09-14 09:26 UTC, kubkon commented on src/sys/unix/bsd/hostcalls_impl.rs
> +
Hmm, in that case I think I'd prefer a pattern match from the readability perspective. All things considered though, no solution here seems particularly elegant unfortunately.

2019-09-14 09:28 UTC, kubkon commented on src/sys/unix/bsd/hostcalls_impl.rs
> +
OK, I've changed it to pattern matching with mutation on `None`. Is that what you've had in mind?

2019-09-14 09:29 UTC, marmistrz commented on src/sys/unix/bsd/hostcalls_impl.rs
> +
Apples & oranges again, for me unwrap or else conveys the meaning more clearly.

2019-09-14 09:30 UTC, marmistrz commented on src/sys/unix/bsd/hostcalls_impl.rs
> +
it's ok, but use an expect for the mutex lock

2019-09-14 10:09 UTC, kubkon commented on src/sys/unix/bsd/hostcalls_impl.rs
> +
Good idea, so how about it we push it even further and throw an actual error instead of panicking? I was thinking of `ENOLCK`.

2019-09-14 10:10 UTC, kubkon commented on src/sys/unix/bsd/hostcalls_impl.rs
> +
I've added `Error::LockError` which resolves to `ENOLCK` :-) Have a look!

2019-09-14 14:31 UTC, sunfishcode commented on src/sys/unix/bsd/hostcalls_impl.rs
> +
The only thing `ENLCK` is used for in POSIX is `fcntl` file locking, so it's not necessarily the best fit here.

`Mutex`es return `PoisonError` after a thread holding the lock panics. The documentation says [it's common to use `unwrap()`](https://doc.rust-lang.org/std/sync/struct.Mutex.html#poisoning) when unlocking, because that effectively means that the panic is propagated to the other thread. I think that's what we want here. When the error occurs, there's already been a panic, which means there's a bug in wasi-common or an upstream dependency, so I think it's appropriate to keep panicking on any thread still trying to access the same `WasiCtx`.

BTW, thinking about threading issues here has me thinking that we should put more of `WasiCtx` behind a `Mutex` or `RwLock`. Right now, lots of WASI functions, like `fd_write`, take an `&mut WasiCtx`, which in Rust means that they should have exclusive access to it. However, nothing in WASI or Wasm prevents multiple threads from calling `fd_write` at the same time. Normally, Rust's borrow checker would protect us, but in this case, the calls may be coming from JIT code :-). But that's obviously outside the scope of this PR.

2019-09-14 18:31 UTC, kubkon commented on src/sys/unix/bsd/hostcalls_impl.rs
> +
Ah, that's good to know! Thanks for elaborating on it :-) I've now reverted the latest commit.

As far as threading issues are concerned, you've raised some interesting points especially since I believe I remember seeing some `Mutex`es and/or `RwLock`s in the original `wasmtime-wasi-c` implementation, so I guess revisiting that in subsequent PRs might indeed be a good idea :-)

2019-09-14 19:00 UTC, kubkon commented
I reckon the PR is in a pretty good state, and I'm inclined to merge it as is. Should any more issues/suggestions come to mind, let's address them in subsequent PRs :-)

2019-09-14 19:01 UTC, merged